<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>Simple Board</title>
</head>
<body>

<#--

<details style="float:left; margin-right: 30%;">
    <summary> <h5>Comments : ${board.commentCount} </h5></summary>
    <p>
        <#list commentList as comment>
    <div style="display: inline-block">
        <h5 style="float: left; margin-right: 10px">[${comment.userName}] ${comment.commentContent} </h5>
        <h5 style="float: right;">Likes:${comment.commentLikes}     ${comment.commentDate}</h5>
    </div>
    </#list>
    </p>
</details>-->


</body>
</html>