<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>join page</title>
</head>
<body>
<h1> join page</h1>

<h3> UserName </h3> <input type="text" name="inputId">
<h3> Password </h3> <input type="password" name="pwd1">
<h3> Validate Password </h3> <input type="password" name="pwd2">
<h3> Email </h3> <input type="email" name="email">

<a href="http://localhost:8081/login/post">
    <input type="button" value="Sign up for SimpleBoard">
</a> <br/><br/>

</body>
</html>