<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>join page</title>
</head>
<body>
<h2>Sign Up</h2>

<form name="join" action="join" method="post">
    <h3> id </h3> <input type="text" name="inputId">
    <h3> Password </h3> <input type="password" name="inputPwd1">
    <h3> Validate Password </h3> <input type="password" name="inputPwd2">
    <h3> Name </h3> <input type="text" name="inputName">
    <h3> Email </h3> <input type="email" name="inputEmail">
    <h3> Phone Number </h3> <input type="tel" name="inputTell">
    <br/><br/>
    <input type="submit" value="Sign up for SimpleBoard">

</form>

</body>
</html>