<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>join page</title>
</head>
<body>
<h2> Sign Up </h2>

<form name="join" action="join" method="post">
    <h3> UserName </h3> <input type="text" name="inputId">
    <h3> Password </h3> <input type="password" name="inputPwd1">
    <h3> Validate Password </h3> <input type="password" name="inputPwd2">
    <h3> Email </h3> <input type="email" name="email">
    <input type="submit" value="Sign up for SimpleBoard">
</form>
<br/><br/>

</body>
</html>