<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>login</title>
</head>
<body>
<h1> login</h1>
<div style="display: inline">
    <a href="http://localhost:8081/"><h3 style="float: left">Simple Board</h3>
    </a>
</div>
<br/>
<form style="float: right; margin-right: 30%;"
      name="search" action="search" method="get">
    <input type="search" name="title" placeholder="search for title">
    <input type="submit" value="SEARCH">
</form>
<br/><br/>

<!--
<h1> Check My Id & Password </h1>
<h3>My ID : ${id}</h3>
<h3>My Password : ${pwd}</h3>
-->

</body>
</html>